apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: slackernews
spec:
  title: SlackerNews
  icon: https://docs.slackernews.io/public/images/slackernews-icon.png
  requireMinimalRBACPrivileges: true
  allowRollback: true
  minKotsVersion: 1.79.0
  ports:
    - serviceName: web
      servicePort: 80
      localPort: 80
      applicationUrl: "http://slackernews-nginx"
  statusInformers:
    - deployment/migrations
    - deployment/slackernews-api
    - deployment/slackernews-frontend
    - deployment/slackernews-nginx
  graphs:
    - title: DAU
      query: 'sum(user_signup_events_total)'
images:
  slackernews_api:
    pullSecret: repl{{ ImagePullSecretName }}
    repository: ghcr.io/slackernews/slackernews-api
  slackernews_migrations:
    pullSecret: repl{{ ImagePullSecretName }}
    repository: ghcr.io/slackernews/slackernews-migrations
  slackernews:
    pullSecret: repl{{ ImagePullSecretName }}
    repository: ghcr.io/slackernews/slackernews-web
