{{ if eq .Values.postgres.deploy_postgres true }}
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: postgres
  name: postgres
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  {{- if ne .Values.postgres.service.nodePort.port nil }}
    nodePort: {{ .Values.postgres.service.nodePort.port }}
  {{- end }}
  selector:
    app: postgres
  type: {{ .Values.postgres.service.type }}
{{ end }}
