apiVersion: v1
kind: Secret
metadata:
  annotations: {}
  labels:
    app: postgres
  name: slackernews-postgres
type: Opaque
stringData:
{{ if eq .Values.postgres.enabled true }}
{{ if eq .Values.postgres.deploy_postgres true }}
  password: '{{ required "A valid .Values.postgres.password is required." .Values.postgres.password }}'
  uri: postgresql://slackernews:{{ .Values.postgres.password }}@postgres/slackernews?connect_timeout=10&application_name=slackernews&sslmode=disable
{{ else }}
  uri: '{{ required "A valid .Values.postgres.uri is required when using an external database." .Values.postgres.uri }}'
{{ end }}
{{ end }}
