{{- if not .Values.slack.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: slackernews-slack
type: Opaque
stringData:
  botToken: "{{ .Values.slack.botToken }}"
  userToken: "{{ .Values.slack.userToken }}"
  clientId: "{{ .Values.slack.clientId }}"
  clientSecret: "{{ .Values.slack.clientSecret }}"
{{- end }}
