apiVersion: v1
kind: Service
metadata:
  labels:
    app: slackernews-frontend
  name: slackernews-frontend
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
{{- if ne .Values.service.nodePort.port nil }}
    nodePort: {{ .Values.service.nodePort.port }}
{{- end }}
  selector:
    app: slackernews-frontend
  type: {{ .Values.service.type }}
