apiVersion: v1
kind: Service
metadata:
  labels:
    app: slackernews-frontend
  name: slackernews-frontend
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: slackernews-frontend
  type: ClusterIP
