name: pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: cd slackernews && yarn
    - name: Install Playwright Browsers
      run: cd slackernews && yarn playwright install --with-deps
    - name: Run Playwright tests
      run: cd slackernews && NODE_ENV=test yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: slackernews/playwright-report/
        retention-days: 30
